
language: cpp

compiler:
  - gcc
cache:
  - apt
os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:hrg/daily
  - sudo apt-get update -qq
  - sudo apt-get install build-essential cmake libeigen3-dev choreonoid libcnoid-dev
  - export EIGEN3_INCLUDE_DIR=/usr/include/eigen3

script:
  - cd src
  - cmake .
  - make -j4
